### ISSUE TITLE
Stack around the variable 'Temp' was corrupted.

### ISSUE THREAD

**Issue by flagstone78** [jgonera/icalendarlib#1]
The functions:
    string Date::Format() const
    Date::operator string() const
in the date.cpp file do not allocate enough space in the char array for the null terminator. This causes the following error when running on visual studio: "Stack around the variable 'Temp' was corrupted"

The code should be:

	string Date::Format() const {
		char Temp[17];
	
		sprintf(Temp, "%.4d/%.2d/%.2d", Data[YEAR], Data[MONTH], Data[DAY]);
	
		if (WithTime == true)
			sprintf(&Temp[10], " %.2d:%.2d", Data[HOUR], Data[MINUTE]);

		return string(Temp);
	}

	Date::operator string() const {
		char Temp[16];
		sprintf(Temp, "%.4d%.2d%.2d", Data[YEAR], Data[MONTH], Data[DAY]);
		if (WithTime == true)
			sprintf(&Temp[8], "T%.2d%.2d%.2d", Data[HOUR], Data[MINUTE], Data[SECOND]);
		return string(Temp);
	}

**Comment by jgonera** [comment]
Sorry, missed this before. Could you make a PR?

**Comment by amidabaya** [comment]
Hello,how can I parser and  ORGANIZERS, ATTENDEE and VTIMEZONE ? Hope your something hope,thanks!

**Comment by jgonera** [comment]
Fixed in https://github.com/jgonera/icalendarlib/pull/2
